- src/client/App.js
- src/client/components/Footer.js
- src/client/components/Main
- src/client/components/Main.js
https://trello.com/c/LlVuJZDM/5-add-main-component
> Task-LlVuJZDM

- src/client/App.js
- src/client/components/Menu.js
Add Menu component
https://trello.com/c/B1baLSTb/4-add-menu-component
> task-B1baLSTb

- src/client/components/Menu.js
Add 5 links to Menu components in paragraph
https://trello.com/c/TokqmLJe/8-add-5-links-to-menu
@AntonShalenui @vkryviak-ua Look at PR
> task-TokqmLJe

- src/client/App.js
- src/client/components/Header.js
https://trello.com/c/JhQ9Jgmu/3-add-header-component
> Task-JhQ9Jgmu create new component Header

- src/client/App.js
- src/client/components/Main.js
Move app implementation into Main
https://trello.com/c/jEZDxpvB/7-move-app-implementation-into-main
> task-jEZDxpvB

- src/client/App.js
Changed **<div> tag** from App render on **<React.Fragment> tag**
https://trello.com/c/x8tLd2Wr/23-app-remove-div
> task-x8tLd2Wr

- src/client/App.js
- src/client/components/Header.js
- src/client/components/header.css
https://trello.com/c/a3dzK6St/11-change-header-text
> Task-a3dzK6St

- src/client/App.js
sorted components in branch
https://trello.com/c/OZuojnSs/16-resort-components
> task-OZuojnSs

- src/client/components/Main.js
- src/client/components/main.css
https://trello.com/c/8gCjnepo/14-style-main-component
> task-8gCjnepo 

- src/client/components/footer.css
Added padding 10px in footer
https://trello.com/c/BfZKvIjo/19-footer-add-padding
> task-BfZKvIjo

- src/client/components/Header.js
- src/client/components/Main.js
https://trello.com/c/Dt4HutPs/27-connect-maincss
> task-Dt4HutPs 

- src/client/components/Menu.js
- src/client/components/menu.css
Added property: Links in menu blue but if you moved cursor over -link changed color to gray and removed underline
https://trello.com/c/LkhxsAxM/21-menu-change-hover
> task-LkhxsAxM

- src/client/components/header.css
task-WmPPecgQ-2
fixed css
https://trello.com/c/WmPPecgQ/18-change-background-for-header
> task-WmPPecgQ-2

- src/client/components/Footer.js
- src/client/components/Header.js
- src/client/components/Main.js
- src/client/components/Menu.js
- src/client/components/footer.css
- src/client/components/header.css
- src/client/components/main.css
- src/client/components/menu.css
Added try namespace for each components
https://trello.com/c/nwWjDm8w/25-app-add-namespace-for-each-components
> task-nwWjDm8w

- src/client/App.js
- src/client/app.css
- src/client/components/Info.js
- src/client/components/info.css
Added new component "Info"(width 100px) and their .css file in opposite side menu.
Displaced the Mine from right: 0; to right: 100px; - made it center
https://trello.com/c/ePphci4j/29-add-new-component-info
@AntonShalenui @vkryviak-ua @RomanBorus Please, take a look
I used aside tags
> task-ePphci4j

- src/client/components/Menu.js
https://trello.com/c/CM2aHFwf/13-fix-warning-in-menu-component
add index parameter and key attribute in menu component
> task-CM2aHFwf 

- src/client/components/Article.js
- src/client/components/Main.js
Added new component "Article" in "Main" component
Added some text "Lorem..."
@vkryviak-ua @AntonShalenui Please look at PR
https://trello.com/c/5w7Mlq0l/30-add-new-component-article
> task-5w7Mlq0l

- src/client/components/Info.js
https://trello.com/c/wLxLFVi0/33-info-add-form
add form in Info component,Add input, textarea and button.
> task-wLxLFVi0 

- src/client/components/Info.js
- src/client/components/info.css
https://trello.com/c/EWbn3D6g/37-info-add-click-on-button
add function pushMe, add click event for it,
add className for button and color red with black border, 
add alert for this button with text "This is a form"
> Task-EWbn3D6g

- src/client/components/info.css
https://trello.com/c/EnGX5by0/38-fix-extra-space-in-info
fix extra space in tags input and textarea
> Task-EnGX5by0

- src/client/components/Menu.js
- src/client/components/menu.css
Added button "Click on me" into menu component.
Button red with black border.
Added click event for it.
Showed alert with text "You are awesome"
https://trello.com/c/F9mdzg4P/32-menu-add-button-and-click
> Task F9mdzg4P-2

- src/client/components/Article.js
https://trello.com/c/sLcUkhmu/31-article-randomize-text
I did that text in article should change for each page refresh. 
add array randomText
add function generateRandomNumber
remove old text in article and changed it for random text.
> task-sLcUkhmu 

- src/client/components/Footer.js
https://trello.com/c/JDWk9FJw/44-footer-change-year
add OnClick on Footer,
add one year to 2019 when presson footer.
> task-JDWk9FJw

- src/client/components/Info.js
https://trello.com/c/pAf0JWj6/40-info-show-message-from-form
Add handlers func for input and textarea
Showed alert with message
Hello {name}. You sad: {description}
> task-pAf0JWj6 

- src/client/components/menu.css
https://trello.com/c/7zMCPTcp/47-menu-update-styles
All position in menu was aligned to left and has 20px padding left. 
Links was become font-size 24px. 
Background image was become in the bottom and it became the same size that menu
> task-7zMCPTcp

- src/client/components/header.css
Updated styles Header. Changed text size to 30px.
Background image did to same size that menu
https://trello.com/c/aKgZPiGr/48-header-update-styles
@vkryviak-ua @AntonShalenui
> task-aKgZPiGr

- src/client/components/Main.js
https://trello.com/c/78KppKzl/42-main-show-text
add click on image with text: "You have pressed on image" after image, 
add in state showTextAfterImage, 
add onclick to image, add function pressTheImage
> task-78KppKzl 

- src/client/components/Menu.js
task-sAj4L8Vd When clicked button in Menu: showed-alert list length
https://trello.com/c/sAj4L8Vd/36-menu-show-list-length
> task-sAj4L8Vd

- src/client/components/Article.js
https://trello.com/c/CZMjEBum/43-article-save-text-index-in-state
save text index in state,
define randomTextIndex with number from generateRandomNumber function
> task-CZMjEBum

- src/client/components/Main.js
- src/client/components/main.css
task-LtFDCXvu added css-property and showed date/time 
https://trello.com/c/LtFDCXvu/46-main-show-date-time
>  task-LtFDCXvu

- src/client/components/Menu.js
If clicked on button added a new url to the end of the list
reformated code, rename button
https://trello.com/c/ujeRgg0J/41-menu-add-link
> task-ujeRgg0J 

- src/client/components/Main.js
Text after image hidden, if you clicked on image one more time
@vkryviak-ua @AntonShalenui 
https://trello.com/c/xq1gAw5v/51-main-hide-text
> task-xq1gAw5v

- src/client/App.js
- src/client/reset.css
added reset.css from https://meyerweb.com/eric/tools/css/reset/index.html
https://trello.com/c/xA9FbWh0/50-app-add-reset-css
> task-xA9FbWh0 
